name: analytica_task
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  firebase_core: ^3.3.0
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  flutter_svg: ^2.0.10+1
  modal_progress_hud_nsn: ^0.5.1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.4.0
  get_storage: ^2.1.1
  uuid: ^4.4.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/icons/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
